# Generated by Django 4.0.4 on 2022-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('pedido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
    ]
