# Generated by Django 4.0.4 on 2022-05-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
    ]
